In [1]:
print("Hello")

Hello


In [3]:
print("Hello World")

Hello World


In [5]:
import numpy as np

In [7]:
np.random.seed(seed=1234)

#Scalar

In [10]:
x = np.array(6)
print ("x: ", x)
print ("x ndim: ", x.ndim) # number of dimensions
print ("x shape:", x.shape) # dimensions
print ("x size: ", x.size) # size of elements
print ("x dtype: ", x.dtype) # data type

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int32


##Vector

In [14]:
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


##Matrix

In [17]:
x = np.array([[1,2], [3,4]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[1 2]
 [3 4]]
x ndim:  2
x shape: (2, 2)
x size:  4
x dtype:  int32


# 3-D Tensor

In [21]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)


x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int32


# Functions


In [28]:
print (np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [30]:
print (np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [32]:
print (np.eye((2)))

[[1. 0.]
 [0. 1.]]


In [34]:
print (np.random.random((2,2)))

[[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


# Indexing

In [37]:
x = np.array([1, 2, 3])

In [39]:
print ("x: ", x)

x:  [1 2 3]


In [41]:
print ("x[0]: ", x[0])

x[0]:  1


In [43]:
x[0] = 0
print ("x: ", x)

x:  [0 2 3]


# Slicing

In [48]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
print ("x column 1: ", x[:, 1])

x column 1:  [ 2  6 10]


In [52]:
print ("x row 0: ", x[0, :])

x row 0:  [1 2 3 4]


In [54]:
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])

x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


# Integer array indexing

In [57]:
print (x)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]


In [59]:
print ("indexed values: ", x[rows_to_get, cols_to_get]) 

indexed values:  [ 1  7 10]


# Basic math

In [62]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or x + y
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y))

x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


# Dot product

In [65]:
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


# Sum across a dimension

In [68]:
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) 

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


# Min/max


In [71]:
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


# Broadcasting

In [74]:
x = np.array([1,2]) # vector
y = np.array(3) # scalar
z = x + y
print ("z:\n", z)

z:
 [4 5]


In [80]:
a = np.array((3, 4, 5))
b = np.expand_dims(a, axis=1)
c = a + b

In [82]:
a.shape # (3,)
b.shape # (3, 1)
c.shape # (3, 3)
print(a)
print(b)
print (c)

[3 4 5]
[[3]
 [4]
 [5]]
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [84]:
a = a.reshape(-1, 1)
a.shape # (3, 1)
c = a + b
c.shape # (3, 1)
print (c)

[[ 6]
 [ 8]
 [10]]


In [86]:
a = a.reshape(-1, 1)
a.shape # (3, 1)
c = a + b
c.shape # (3, 1)
print (c)

[[ 6]
 [ 8]
 [10]]


In [88]:
a = np.array([3, 4, 5])
a.shape # (3,)
a = a.reshape(-1, 1)
a.shape 

(3, 1)

# Transposing

In [91]:
x = np.array([[1,2,3], [4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("y:\n", y)
print ("y.shape: ", y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]]
y.shape:  (3, 2)


In [93]:
x = np.array([[1,2,3,4,5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y: \n", y)
print ("y.shape: ", y.shape)
z = np.reshape(x, (2, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


# Joining

In [95]:
x = np.random.random((2, 3))
print (x)
print (x.shape)

[[0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263]]
(2, 3)


# Concatenation


In [105]:
y = np.concatenate([x, x], axis=0) # concat on a specified axis
print (y)
print (y.shape)

[[0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263]
 [0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263]]
(4, 3)


In [107]:
y = np.concatenate([x, x], axis=1) # concat on a specified axis
print (y)
print (y.shape)

[[0.77997581 0.27259261 0.27646426 0.77997581 0.27259261 0.27646426]
 [0.80187218 0.95813935 0.87593263 0.80187218 0.95813935 0.87593263]]
(2, 6)


# Stacking


In [116]:
z = np.stack([x, x], axis=1) # stack on new axis
print (z)
print (z.shape)


[[[0.77997581 0.27259261 0.27646426]
  [0.77997581 0.27259261 0.27646426]]

 [[0.80187218 0.95813935 0.87593263]
  [0.80187218 0.95813935 0.87593263]]]
(2, 2, 3)


# Expanding / reducing

In [119]:
# Adding dimensions
x = np.array([[1,2,3],[4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # expand dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)   # notice extra set of brackets are added

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [121]:
# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x, 1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape) 

x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
